{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resilienceAgent.name" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
