version: '3.9'

services:
  agent:
    build:
      context: .
      dockerfile: docker/AgentDockerfile
    restart: unless-stopped
    command: poetry run resilience-agent
    volumes:
      - ./src/agent:/home/src/agent
    environment:
      - RESILTY_RESILIENCE_AGENT_API_KEY_ID=test
      - RESILTY_RESILIENCE_AGENT_API_SECRET_KEY=test
    depends_on:
      - controlplane
  controlplane:
    build:
      context: .
      dockerfile: docker/MockserverDockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: >
      uvicorn server.app:app
      --host 0.0.0.0
      --port 8000
      --reload
    volumes:
      - ./mockserver/server:/home/server
