namespace: resiltyio
nameOverride: resilience-agent
fullnameOverride: "Resilience Agent"

workload:
  type: daemonset

serviceAccount:
    create: true
    name: resilience-agent-sa

image:
  repository: resilience-agent
  tag: local

service:
  enabled: false

ingress:
  enabled: false

livenessProbe:
  exec:
    command:
      - "sh"
      - "-c"
      - "pgrep -f 'resilience-agent' || exit 1"
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  exec:
    command:
      - "sh"
      - "-c"
      - "pgrep -f 'resilience-agent' || exit 1"
  initialDelaySeconds: 10
  periodSeconds: 10

autoscaling:
  enabled: false

environment_variable:
  enabled: true
  data:
    ENV: local
    LOG_LEVEL: INFO
    RESILTY_AGENT_CONTROL_PLANE_API_HOST: http://resilience-agent-cp.resiltyio.svc.cluster.local:8000

migration:
  enabled: false

wsgiConfig:
  enabled: false


rbac:
  enabled: true
  clusterRoleName: resiltio-clusterrole
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch", "delete"]
    - apiGroups: [""]
      resources: ["pods/exec"]
      verbs: ["get", "create"]
    - apiGroups: ["apps"]
      resources: ["deployments", "statefulsets"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["autoscaling"]
      resources: ["horizontalpodautoscalers"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["policy"]
      resources: ["poddisruptionbudgets"]
      verbs: ["get", "list", "watch"]
    - apiGroups: ["metrics.k8s.io"]
      resources: ["pods"]
      verbs: ["get", "list"]
  namespaces:
    - "nginx"


containerCommand:
  - "poetry"
  - "run"
  - "resilience-agent"
