namespace: resiltyio
nameOverride: agent
fullnameOverride: "Resilience Agent"

workload:
  type: deployment

replicaCount: 2

autoscaling:
  enabled: false

serviceAccount:
    create: true
    name: agent-sa

image:
  repository: resilience-agent
  tag: ""

service:
  enabled: false

ingress:
  enabled: false

livenessProbe:
  exec:
    command:
      - "sh"
      - "-c"
      - "pgrep -f 'resilience-agent' || exit 1"
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  exec:
    command:
      - "sh"
      - "-c"
      - "pgrep -f 'resilience-agent' || exit 1"
  initialDelaySeconds: 10
  periodSeconds: 10

environment_variable:
  enabled: true
  data:
    LOG_LEVEL: INFO
    LOG_MAX_MB: "50"
    LOG_BACKUP_COUNT: "5"

migration:
  enabled: false

rbac:
  enabled: true
  namespaced:
    roleName: resiltyio-rabc-ns
    namespaces:
      - nginx
      - http-echo
    rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list", "watch", "delete"]
      - apiGroups: [""]
        resources: ["pods/exec"]
        verbs: ["get", "create"]
      - apiGroups: ["apps"]
        resources: ["deployments"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["autoscaling"]
        resources: ["horizontalpodautoscalers"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["policy"]
        resources: ["poddisruptionbudgets"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["metrics.k8s.io"]
        resources: ["pods"]
        verbs: ["get", "list"]

  cluster:
    roleName: resiltyio-rabc-cluster
    rules:
      # Kubernetes version endpoint (non-resource URL)
      - nonResourceURLs: ["/version"]
        verbs: ["get"]

volumeMounts:
  - name: agent-logs
    mountPath: /var/log/agent


volumes:
  - name: agent-logs
    emptyDir:
      sizeLimit: 500Mi


containerCommand: ["poetry","run","resilience-agent"]
