region:
  name: eu
  endpoints:
    eu:
      env: eu
      controlPlaneApiHost: https://runtime-stg.resilopshq.dev
      authServiceHost: https://auth-stg.resilopshq.dev
      fluentBitRemoteHost: runtime-stg.resilopshq.eu
      fluentBitRemotePort: "443"
      fluentBitRemoteTls: "On"
