secrets:
    RESILTY_AGENT_AUTH_SERVICE_CLIENT_ID: ENC[AES256_GCM,data:EzgPvA==,iv:z59rAFA31aqCZdj8v3/Krlmg7t7slp8HS31WdgqoQbI=,tag:FcdWELVeHUkrN1LQlul4kg==,type:str]
    RESILTY_AGENT_AUTH_SERVICE_CLIENT_SECRET: ENC[AES256_GCM,data:4LL3qg==,iv:PqhthuBTzkqXwePse/zJIig3YC5Wy61EZBo8gUiGpUk=,tag:yZXESz9QYggu1+BzbAFk7g==,type:str]
sops:
    lastmodified: "2026-04-04T09:39:00Z"
    mac: ENC[AES256_GCM,data:22bEznoLtVKRe8MaInozV2f2vCUjB7ZimzifeSDKh6LNzW/+qBBB9lIPxwzcP8ghBKpbK5u2fSPtYIndxPJxRmpVw6vlN4bTUNB9ThdEc388jFVkSetXLGLnfyiQkvCzYr1bXKEgpXhgYF6Krt9q2rs6nRwVotntwEHlQbimug8=,iv:GW5BlVd6FqO12wkYXTNcIIYOzYzcmSfrXLE387Z0ENI=,tag:yNnezHMBfEIZmi9ntvm9Lg==,type:str]
    pgp:
        - created_at: "2025-08-21T19:37:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA+4CW24jXh2nAQv9ESXfG/pS9klYeh2nxpyb3Rt/qPbi5a4GJlVRMG0xECCC
            RqTozmY1L7PB0Mq3CBXQYmR98HZrIIUxUgMh5+bEK+O0UhkMLwTU68a8TGcazuPX
            3UxAk4LdRi1yvXsr5Fst/Bf6CVHiDfFrq9N65g0ZEOGRqX3Wg06JkV39/H0pa0yP
            3u3QBmUTQnWdUJVs86mOxTvcXl7nX8/FCpmCT+Aw+7Qty76UtxJAnxhiSmi/aI+D
            7iHogKz0bjCk8mZeia9ACQ6qFNZKZK2XNZGDrM9i4kdyznzdMclpclpc1fdcRzJp
            VXYsqFg50eVnsgCs1kNZ9xybgwVtCJMQBBnUb3i2xpLpGQiEafF4n7k2Qn3y9bhz
            SqxKUBZbXhmSN3zNaQZSbV7YQVHsfzOjvyLGlnyrVhOMWcix5MY1XKDPQjRC/chu
            N3qDTm6nH/kVtVCgZioHW7XEaQgcLEzGhiaaP/+HRA5UZu/2evUm/LzCeZqKIvBK
            xNGaWS/k69XKeCocXRKO1GYBCQIQ1KHLVL+JxuqNLJ9PcIlP7ZsdbtkMDFDDNDOS
            TGmoYo+/89Fckb3pI/JQ17GDR+5UhxhvtNT9dEFXEb89wQbW1fgkFh8Z2F5LF1YS
            vsW115QDacnORZiyPBDaQaRQk23rUlA=
            =t2BN
            -----END PGP MESSAGE-----
          fp: A9ACD1E4BCCD808F0937E18920CBCEBF0DE0870C
    encrypted_regex: .*
    version: 3.10.2
