secrets:
    RESILTY_AGENT_AUTH_SERVICE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:UaFNtQ==,iv:HzDtsEj58eQc1sYshmxjlBKU26Ybf1G/mD96fP48F2w=,tag:vkeicrIU2B+ksiIlrtZG+w==,type:str]
    RESILTY_AGENT_AUTH_SERVICE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:SQdsWw==,iv:yFxEV9+0LdYQ4K9DWCQlca5VFYJu31IbqS4auXzAlNY=,tag:nncLS+zgLJ33y3rhJX+2xQ==,type:str]
sops:
    lastmodified: "2026-04-04T07:37:00Z"
    mac: ENC[AES256_GCM,data:firGw26VQvAVybXUPxvDpLY/EgrUyQL87uu43dl2Nfiy2SCjoH+5QUeDjOeQvyi0v3x9hKIfbUzhdF3ezeyrO+RICyOAp5NleHLqWxA2EXUE3QDbGbU4Lnz3rxTSa3tf4Z1VagdmJuL4lBrr52s/Bq8aUZWLVnVutKehQhAF4no=,iv:hj4aJJSyoF3sgtJViyp3wPpc6k2Mnwtm9WaUm9quLSI=,tag:t952epX6FXt0ONh7V62n2w==,type:str]
    pgp:
        - created_at: "2025-08-21T19:37:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA+4CW24jXh2nAQv9ESXfG/pS9klYeh2nxpyb3Rt/qPbi5a4GJlVRMG0xECCC
            RqTozmY1L7PB0Mq3CBXQYmR98HZrIIUxUgMh5+bEK+O0UhkMLwTU68a8TGcazuPX
            3UxAk4LdRi1yvXsr5Fst/Bf6CVHiDfFrq9N65g0ZEOGRqX3Wg06JkV39/H0pa0yP
            3u3QBmUTQnWdUJVs86mOxTvcXl7nX8/FCpmCT+Aw+7Qty76UtxJAnxhiSmi/aI+D
            7iHogKz0bjCk8mZeia9ACQ6qFNZKZK2XNZGDrM9i4kdyznzdMclpclpc1fdcRzJp
            VXYsqFg50eVnsgCs1kNZ9xybgwVtCJMQBBnUb3i2xpLpGQiEafF4n7k2Qn3y9bhz
            SqxKUBZbXhmSN3zNaQZSbV7YQVHsfzOjvyLGlnyrVhOMWcix5MY1XKDPQjRC/chu
            N3qDTm6nH/kVtVCgZioHW7XEaQgcLEzGhiaaP/+HRA5UZu/2evUm/LzCeZqKIvBK
            xNGaWS/k69XKeCocXRKO1GYBCQIQ1KHLVL+JxuqNLJ9PcIlP7ZsdbtkMDFDDNDOS
            TGmoYo+/89Fckb3pI/JQ17GDR+5UhxhvtNT9dEFXEb89wQbW1fgkFh8Z2F5LF1YS
            vsW115QDacnORZiyPBDaQaRQk23rUlA=
            =t2BN
            -----END PGP MESSAGE-----
          fp: A9ACD1E4BCCD808F0937E18920CBCEBF0DE0870C
    encrypted_regex: .*
    version: 3.10.2
