image:
  repository: resilience-agent
  tag: local

replicaCount: 2

envVar:
  enabled: true
  data:
    ENV: local
    RESILTY_AGENT_CONTROL_PLANE_API_HOST: http://controlplane.resiltyio.svc.cluster.local:8000
    RESILTY_AGENT_AUTH_SERVICE_HOST: http://controlplane.resiltyio.svc.cluster.local:8000


sidecar:
  env:
    - name: FLUENTBIT_REMOTE_HOST
      value: controlplane.resiltyio.svc.cluster.local
    - name: FLUENTBIT_REMOTE_PORT
      value: "8000"
    - name: FLUENTBIT_REMOTE_TLS
      value: "Off"
    - name: FLUENTBIT_OAUTH_TOKEN_URL
      value: "https://controlplane.resiltyio.svc.cluster.local/api/v1/m2m/token"
    - name: FLUENTBIT_OAUTH_SCOPES
      value: "res:oauth:scope:events:create res:oauth:scope:metrics:create"
