image:
  repository: resilience-agent
  tag: local

replicaCount: 2

envVar:
  enabled: true
  data:
    ENV: local
    RESILOPS_AGENT_CONTROL_PLANE_API_HOST: http://host.minikube.internal:9000
    RESILOPS_AGENT_AUTH_SERVICE_HOST: http://host.minikube.internal:8000


sidecar:
  env:
    - name: FLUENTBIT_REMOTE_HOST
      value: host.minikube.internal
    - name: FLUENTBIT_REMOTE_PORT
      value: "9000"
    - name: FLUENTBIT_REMOTE_TLS
      value: "Off"
    - name: FLUENTBIT_OAUTH_TOKEN_URL
      value: "http://host.minikube.internal:8000/api/v1/m2m/token"
    - name: FLUENTBIT_OAUTH_SCOPES
      value: "res:oauth:scope:events:create res:oauth:scope:metrics:create"
